language: go
go:
- '1.10'
env:
- NODE_VERSION="6"
before_install:
- nvm install $NODE_VERSION
install:
- npm install
script:
- go test
- npm test
addons:
  sauce_connect:
    username: jbelmont
    access_key:
      secure: lQMvtm7hg+ST7n7WMqnwh8uuST2Bs7Qbb/qCCaVWYvqogDY+bu1oDdtBuOKPsXFb9kVi3PU/tJHRR3fEoHzFlrd91x2mcCeNnJkytVsakU8soYt16X8OFu34ZsUkhyu8SfvXTOEaLhP3BnEsEtA6saTw3azhnkOg2ZawcYSVHVn80nhLN4yA8W2kiOnI/YUIM7CZyvwYCohaqAjXNXmNOHYoyH9h/1mIHSDs0z41BhMaNOJqk762fqZWdukYaOxWMSYRwGBwMymhsFj2ulZlAnO4xO9ZBr/CGZeTUDqIphdKdx3JR1WWnKZYTQjuJWvHTvbBXkaoB6mnkEYmC2RrGdtmRAsNe9UAY0FMo493la4+mZgqLcFVxB6XY07Y5akESCvehCXASCcBYDmH68NR0Zfyu0L3Zhi6h4C9EDR5IiR6sbkynN+a3WvO4uCgo+5dpkoe2hJYc+Y/CyXzcoade67onLQVF/suQKw8HJgHdY8tza5sFSGiabiyYWncI78pTiB6yUdvL1b9Qeccf83juA3MnLGm2eiMRUxNlnlmoelmsoie2yP780mKJuCHMJzLT3PZC17Ft0iV7FwhlpU7ubNOFS8BgcMdb1aD/Zeoi1LDpfNyG7BEP6ncy6KCvkopEeKl3MosAgZWFATrME/kwGVuPGMxRMuz07qpSZ608b8=
